import type { PresetData } from './useMockupStore';

/**
 * Curated cinematic looks (Phase 3). Each preset is a Partial<MockupState>
 * JSON snapshot — loaded via store.loadPreset(). User-saved presets follow
 * the exact same shape (see ExportBar / ControlPanel save).
 */
export type NamedPreset = {
  name: string;
  /** marketing-y blurb shown in the picker */
  hint: string;
  /** Pro-only premium pack member (Phase 5 gate point) */
  pro?: boolean;
  data: PresetData;
};

export const PRESETS: NamedPreset[] = [
  {
    name: 'Studio Soft',
    hint: 'Clean product-shot. Soft key, neutral fill.',
    data: {
      azimuth: 35,
      polar: 58,
      distance: 9,
      focalLength: 85,
      hdriPreset: 'studio',
      keyColor: '#ffffff',
      keyIntensity: 1.4,
      fillColor: '#cfe0ff',
      fillIntensity: 0.55,
      rimColor: '#ffffff',
      rimIntensity: 1.6,
      bloom: 0.55,
      vignette: 0.3,
      chromaticAberration: 0.0006,
      grain: 0.05,
      bgMode: 'gradient',
      bgColorA: '#23262e',
      bgColorB: '#0a0b0f',
      exposure: 1.0,
      contrast: 1.05,
    },
  },
  {
    name: 'Moody Noir',
    hint: 'High-contrast, deep shadows, single hard rim.',
    data: {
      azimuth: 48,
      polar: 64,
      distance: 9.5,
      focalLength: 105,
      hdriPreset: 'night',
      keyColor: '#dfe7ff',
      keyIntensity: 1.1,
      fillColor: '#26324d',
      fillIntensity: 0.2,
      rimColor: '#9fb6ff',
      rimIntensity: 2.4,
      bloom: 0.7,
      vignette: 0.6,
      chromaticAberration: 0.0012,
      grain: 0.12,
      bgMode: 'gradient',
      bgColorA: '#0d1018',
      bgColorB: '#000000',
      exposure: 0.92,
      contrast: 1.18,
      aperture: 2.2,
      bokehScale: 6,
    },
  },
  {
    name: 'Bright SaaS',
    hint: 'Airy, light, marketing-page friendly.',
    data: {
      azimuth: 28,
      polar: 54,
      distance: 8.6,
      focalLength: 70,
      hdriPreset: 'apartment',
      keyColor: '#ffffff',
      keyIntensity: 1.5,
      fillColor: '#ffffff',
      fillIntensity: 0.8,
      rimColor: '#eaf2ff',
      rimIntensity: 1.2,
      bloom: 0.45,
      vignette: 0.18,
      chromaticAberration: 0.0004,
      grain: 0.03,
      bgMode: 'gradient',
      bgColorA: '#f4f6fb',
      bgColorB: '#d9e2f2',
      exposure: 1.08,
      contrast: 1.0,
      aperture: 4,
      bokehScale: 3,
    },
  },
  {
    name: 'Golden Hour',
    hint: 'Warm sunset key, long lens, dreamy bokeh.',
    data: {
      azimuth: 42,
      polar: 60,
      distance: 9.2,
      focalLength: 105,
      hdriPreset: 'sunset',
      keyColor: '#ffd9a0',
      keyIntensity: 1.5,
      fillColor: '#ffb27a',
      fillIntensity: 0.4,
      rimColor: '#fff0d6',
      rimIntensity: 2.0,
      bloom: 0.8,
      vignette: 0.4,
      chromaticAberration: 0.001,
      grain: 0.07,
      bgMode: 'gradient',
      bgColorA: '#3a2417',
      bgColorB: '#120a06',
      exposure: 1.05,
      contrast: 1.08,
      aperture: 2.0,
      bokehScale: 6,
    },
  },
  {
    name: 'Neon',
    hint: 'Synthwave rim glow on near-black.',
    pro: true,
    data: {
      azimuth: 50,
      polar: 62,
      distance: 9.4,
      focalLength: 90,
      hdriPreset: 'night',
      keyColor: '#7af2ff',
      keyIntensity: 1.2,
      fillColor: '#ff5db1',
      fillIntensity: 0.5,
      rimColor: '#b07cff',
      rimIntensity: 2.6,
      bloom: 1.0,
      vignette: 0.5,
      chromaticAberration: 0.002,
      grain: 0.1,
      bgMode: 'gradient',
      bgColorA: '#160a26',
      bgColorB: '#04020a',
      exposure: 1.0,
      contrast: 1.12,
      aperture: 2.4,
      bokehScale: 7,
    },
  },
];
